#pragma once

#ifdef ESP_PLATFORM
#define ENVIRONMENT "ESP-IDF"

#define STORAGE_CONFIG_FILNAME "config.txt"

#define WIFI_DEFAULT_SSID "OpenQS_AP"
#define WIFI_DEFAULT_PWD "00000000"

#define OTA_DIAGNOSTIC_PIN 13
#define OTA_RECEIVER_TIMEOUT 3000
#define OTA_UDP_RECEIVER_PORT 3232
#define OTA_UDP_BUFFER_SIZE 256
#define OTA_TCP_BUFFER_SIZE 1024
#define OTA_VERIFY_HASH_CODE_LENGTH 16
#define OTA_VERIFY_HASH_DECODE_LENGTH (OTA_VERIFY_HASH_CODE_LENGTH * 2 + 1)

#define FUNC_PIN 4

#define CUTOFF_PIN DAC_CHAN_0 // GPIO25

#define ENGINESPEED_PIN 34
#define ENGINESPEED_MAXIMUM_SAMPLERATE 10000 // 100HZ
#define ENGINESPEED_ACTIVE_FREQ 1            // 1HZ
#define MINIMUM_ENGINESPEED 600
#define MAXIMUM_ENGINESPEED 16000

#define ADC_SAMPLERATE 5        // Hz
#define TEMP_PIN ADC1_CHANNEL_7 // GPIO35
#define VOLT_PIN ADC1_CHANNEL_3 // GPIO39

#define VOLT_ADC_R1 10000
#define VOLT_ADC_R2 47000

#define TEMP_ADC_R1 1000
#define TEMP_ADC_R2_THERMISTOR_T1 10000 // Thermistor Resistance At Temperature 25
#define TEMP_ADC_R2_THERMISTOR_T2 1000  // Thermistor Resistance At Temperature 100
#define THERMISTOR_SOURCE_VOLT 3300     // Thermistor Source Voltage 3300mV = 3.3V

#define ADCTOVOLT(ADC_RAWDATA) ((ADC_RAWDATA / 1000.0) * ((VOLT_ADC_R1 + VOLT_ADC_R2) / (VOLT_ADC_R1 * 1.0)))
#define ADCTOTEMP(ADC_RAWDATA) ((ADC_RAWDATA * TEMP_LINEAR_COEFF) + TEMP_LINEAR_OFFSET)
#define TEMP_ADC_VOLTAGE_T1 (THERMISTOR_SOURCE_VOLT * TEMP_ADC_R2_THERMISTOR_T1 / (TEMP_ADC_R1 + TEMP_ADC_R2_THERMISTOR_T1))
#define TEMP_ADC_VOLTAGE_T2 (THERMISTOR_SOURCE_VOLT * TEMP_ADC_R2_THERMISTOR_T2 / (TEMP_ADC_R1 + TEMP_ADC_R2_THERMISTOR_T2))
#define TEMP_LINEAR_COEFF ((100.0 - 25.0) / (TEMP_ADC_VOLTAGE_T2 - TEMP_ADC_VOLTAGE_T1))
#define TEMP_LINEAR_OFFSET (25.0 - (TEMP_LINEAR_COEFF * TEMP_ADC_VOLTAGE_T1))

#define BLINK_PIN 2
#define BLINK_DEFAULT_FREQ 1

#define BUZZER_PIN 21
#define BUZZER_DEFAULT_FREQUENCY 1000
#define BUZZER_ENCODE_RESOLUTION 8

#define HX711_CLOCK_PIN 19
#define HX711_DOUT_PIN 18
#define HX711_AVERAGE_NUM 10

#define I2C_CLACK_FREQ 400000
#define MPU_SCL_PIN 22
#define MPU_SDA_PIN 23

#define ACCEL_CONFIG ACCEL_CONFIG_4G
#define GYRO_CONFIG GYRO_CONFIG_500

#elif defined(ARDUINO)
#define ENVIRONMENT "ARDUINO"
#else
#error "Unknown Environment"
#endif